# Generated by Django 3.0.5 on 2020-04-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200417_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': 'posts'},
        ),
    ]
